### ISSUE TITLE
dev: consider sonia-corporation/stale instead of actions/stale

### ISSUE THREAD

**Issue by rootwork** [dec0dOS/amazing-github-template#10]
I recently switched from [actions/stale](https://github.com/actions/stale) to [sonia-corporation/stale](https://github.com/sonia-corporation/stale).

actions/stale [appears to have no further active development](https://github.com/actions/stale/issues/650#issuecomment-1009681386), and sonia-corporation/stale has a nice feature: exempting from marking as stale all issues that are in a project (along with issues that are in milestones, or assigned to someone, both of which actions/stale already had). So if people are proposing features, simply accepting them by adding them to a project, like say a version release plan, will keep them from being marked stale without having to add extra labels.

sonia-corporation/stale also has a much more comprehensive documentation site: https://sonia-corporation.github.io/stale/

The Yaml keys in the workflow have different names but there's basically a 1:1 correspondence, so it was very fast to update my existing workflow to [a new one](https://github.com/premail/premail/blob/main/.github/workflows/stale.yml).

Anyway just passing this along in case it's helpful!

**Comment by dec0dOS** [comment]
@rootwork, thanks a lot for sharing!
Seems to be that some commits has been done three days ago in the `main` branch. Is it really doesn't have any further development anymore?

**Comment by rootwork** [comment]
@dec0dOS You're right! Maybe it is in fact still in active development.

I appreciated the sonia version for its project option, but if that's not generally applicable then maybe actions/stale is still fine.
