### ISSUE TITLE
feat: Wording/language cleanup

### ISSUE THREAD

**Issue by rootwork** [dec0dOS/amazing-github-template#3]
# Feature Request

**Describe the Feature Request**

There is some wording in some places that seems a little clunky or unclear -- I'm not sure if this is a translation issue or something else, but I thought I could offer some suggestions for making things more straightforward.

**Describe Preferred Solution**

Happy to make a PR with suggestions if you're open to it.

**Describe Alternatives**

N/A

**Related Code**

N/A

**Additional Context**

I don't have any, but I could probably find style guides etc. if you want "objective" citations for my opinions on things :)

**If the feature request is approved, would you be willing to submit a PR?**
**Yes** / No _(Help can be provided if you need assistance submitting a PR)_

**Comment by dec0dOS** [comment]
Hello, @rootwork!
I'm looking forward to your suggestions!

**Comment by rootwork** [comment]
This was merged, so closing.
